# Generated by ishou-render::base16_nix — DO NOT EDIT
# Source of truth: pleme-io/ishou/crates/ishou-tokens/src/color.rs
# Architecture:    pleme-io/theory/THEME-ARCHITECTURE.md
#
# base16 as an ALREADY-PARSED attrset. Consumed as:
#   stylix.base16Scheme = import ./rendered/stylix-base16-nord-dark.nix;
#
# The `{ yaml = <derivation>; }` form this replaces made stylix
# readFile a derivation — an IFD — which forced a linux build during
# evaluation and left every NixOS node unevaluable from a Mac.
{
  system = "base16";
  name = "Nord (pleme-io / ishou)";
  author = "Arctic Ice Studio; mapped by pleme-io ishou";
  variant = "dark";
  slug = "nord-dark";
  base00 = "2e3440";
  base01 = "3b4252";
  base02 = "434c5e";
  base03 = "4c566a";
  base04 = "d8dee9";
  base05 = "e5e9f0";
  base06 = "eceff4";
  base07 = "8fbcbb";
  base08 = "bf616a";
  base09 = "d08770";
  base0A = "ebcb8b";
  base0B = "a3be8c";
  base0C = "88c0d0";
  base0D = "81a1c1";
  base0E = "b48ead";
  base0F = "5e81ac";
}
