# Generated by ishou-render::stylix_fonts — DO NOT EDIT
# Source of truth: pleme-io/ishou/crates/ishou-tokens/src/typography.rs
# Architecture:    pleme-io/theory/THEME-ARCHITECTURE.md
#
# Consumed as `stylix.fonts = import this { inherit pkgs; };`
# in the fleet's darwin / home-manager configuration.
{ pkgs }:
{
  # Source of every ASCII glyph the fleet's terminals draw.
  monospace = {
    name = "JetBrainsMono Nerd Font";
    package = pkgs.nerd-fonts.jetbrains-mono;
  };

  # Canonical pleme-io sans for GTK / Cocoa app text.
  sansSerif = {
    name = "Inter";
    package = pkgs.inter;
  };

  # DejaVu Serif ships on every nixpkgs-supported platform —
  # earlier `pkgs.charter` reference broke flake-eval.
  serif = {
    name = "DejaVu Serif";
    package = pkgs.dejavu_fonts;
  };

  # nixpkgs renamed noto-fonts-emoji → noto-fonts-color-emoji;
  # macOS apps prefer the system Apple Color Emoji at runtime.
  emoji = {
    name = "Noto Color Emoji";
    package = pkgs.noto-fonts-color-emoji;
  };
}
