# Generated by ishou-render::vellum — DO NOT EDIT
# Source of truth: pleme-io/ishou/crates/ishou-tokens/src/vellum.rs
#
# Vellum base16 as an ALREADY-PARSED attrset. Consumed as:
#   stylix.base16Scheme = import ./rendered/stylix-base16-vellum.nix;
#
# The `{ yaml = <derivation>; }` form this replaces made stylix
# readFile a derivation — an IFD — which forced a linux build during
# evaluation and left every NixOS node unevaluable from a Mac.
{
  system = "base16";
  name = "Vellum";
  author = "pleme-io (ishou)";
  variant = "dark";
  slug = "vellum";
  base00 = "16140e";
  base01 = "1f1c15";
  base02 = "3a343e";
  base03 = "90897b";
  base04 = "ada593";
  base05 = "e2dbc8";
  base06 = "ede6d6";
  base07 = "f4efe2";
  base08 = "c9837b";
  base09 = "cb9070";
  base0A = "d7c489";
  base0B = "a9bb8c";
  base0C = "94bbb8";
  base0D = "99aabe";
  base0E = "b8a1b9";
  base0F = "b3886c";
}
