//! Nix renderer — emits an importable Nix expression for the Nord
//! palette in the shape every pleme-io HM wrapper historically carried
//! locally (`{ polar = { night0 = "…"; … }; snow = …; frost = …;
//! aurora = …; }`).
//!
//! Closes the M5 `no-foreign-nord-source` invariant for the
//! `blackmatter-ghostty` / `blackmatter-mado` / `blackmatter-opencode`
//! wrappers: each currently `import ./module/themes/nord/colors.nix`
//! their own copy of the palette. After M6.1 they `import` the
//! `ishou.packages.${system}.nord-palette-nix` build artifact instead,
//! the local files are deleted, and the fleet has one Nord.
//!
//! Output is byte-stable: a future operator who runs
//! `nix run github:pleme-io/ishou#nix` always gets the same bytes for
//! the same TokenSet. The shape is intentionally compatible with the
//! retiring colors.nix files so the migration is a one-line
//! import-path swap.

use ishou_tokens::{Rgb, TokenSet};

/// Render the canonical pleme-io Nord palette as an importable Nix
/// attrset. Hex values are uppercase with `#` prefix — matches the
/// shape every retiring `module/themes/nord/colors.nix` carried.
#[must_use]
pub fn render(t: &TokenSet) -> String {
    let c = &t.color;
    let mut out = String::new();
    out.push_str("# Generated by ishou-render::nix — DO NOT EDIT\n");
    out.push_str("# Source of truth: pleme-io/ishou/crates/ishou-tokens/src/color.rs\n");
    out.push_str("# Architecture:    pleme-io/theory/THEME-ARCHITECTURE.md\n");
    out.push_str("# Shape compatible with the legacy\n");
    out.push_str("# `<wrapper>/module/themes/nord/colors.nix` files this output\n");
    out.push_str("# replaces — import the package and consume identically.\n");
    out.push_str("{\n");
    out.push_str("  polar = {\n");
    push_field(&mut out, "    ", "night0", c.polar_night_0);
    push_field(&mut out, "    ", "night1", c.polar_night_1);
    push_field(&mut out, "    ", "night2", c.polar_night_2);
    push_field(&mut out, "    ", "night3", c.polar_night_3);
    out.push_str("  };\n\n");
    out.push_str("  snow = {\n");
    push_field(&mut out, "    ", "storm0", c.snow_storm_0);
    push_field(&mut out, "    ", "storm1", c.snow_storm_1);
    push_field(&mut out, "    ", "storm2", c.snow_storm_2);
    out.push_str("  };\n\n");
    out.push_str("  frost = {\n");
    push_field(&mut out, "    ", "frost0", c.frost_0);
    push_field(&mut out, "    ", "frost1", c.frost_1);
    push_field(&mut out, "    ", "frost2", c.frost_2);
    push_field(&mut out, "    ", "frost3", c.frost_3);
    out.push_str("  };\n\n");
    out.push_str("  aurora = {\n");
    push_field(&mut out, "    ", "red", c.aurora_red);
    push_field(&mut out, "    ", "orange", c.aurora_orange);
    push_field(&mut out, "    ", "yellow", c.aurora_yellow);
    push_field(&mut out, "    ", "green", c.aurora_green);
    push_field(&mut out, "    ", "purple", c.aurora_purple);
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

fn push_field(out: &mut String, indent: &str, name: &str, rgb: Rgb) {
    out.push_str(&format!(
        "{}{} = \"#{:02X}{:02X}{:02X}\";\n",
        indent, name, rgb.r, rgb.g, rgb.b
    ));
}

#[cfg(test)]
mod tests {
    use super::*;
    use ishou_tokens::TokenSet;

    #[test]
    fn deterministic() {
        let t = TokenSet::pleme();
        assert_eq!(render(&t), render(&t));
    }

    #[test]
    fn matches_legacy_blackmatter_ghostty_colors_nix() {
        // Byte-for-byte snapshot of the canonical Nord attrset the
        // three retiring HM wrappers each carried locally. The headers
        // differ (legacy is a one-line `# Nord Color Palette` comment;
        // ishou's render emits provenance) but the structural body is
        // identical so `import` consumers see the same shape.
        let out = render(&TokenSet::pleme());
        let expected_body = "\
{
  polar = {
    night0 = \"#2E3440\";
    night1 = \"#3B4252\";
    night2 = \"#434C5E\";
    night3 = \"#4C566A\";
  };

  snow = {
    storm0 = \"#D8DEE9\";
    storm1 = \"#E5E9F0\";
    storm2 = \"#ECEFF4\";
  };

  frost = {
    frost0 = \"#8FBCBB\";
    frost1 = \"#88C0D0\";
    frost2 = \"#81A1C1\";
    frost3 = \"#5E81AC\";
  };

  aurora = {
    red = \"#BF616A\";
    orange = \"#D08770\";
    yellow = \"#EBCB8B\";
    green = \"#A3BE8C\";
    purple = \"#B48EAD\";
  };
}
";
        assert!(
            out.ends_with(expected_body),
            "rendered output's body must match the legacy colors.nix exactly:\n--- got ---\n{out}--- expected end ---\n{expected_body}"
        );
    }

    #[test]
    fn nord_polar_night_0_lands_at_polar_night0() {
        let out = render(&TokenSet::pleme());
        assert!(out.contains("night0 = \"#2E3440\""), "got:\n{out}");
    }

    #[test]
    fn header_documents_provenance() {
        let out = render(&TokenSet::pleme());
        assert!(out.contains("THEME-ARCHITECTURE.md"));
        assert!(out.contains("Source of truth"));
    }
}
