//! Stylix fonts renderer — emits the Nix attrset shape
//! `stylix.fonts.*` consumes (`{ monospace = { name = …; package = …; };
//! sansSerif = …; serif = …; emoji = …; }`).
//!
//! Closes the loop: just as the `stylix` render target sources the
//! fleet's base16 palette from ishou's single Nord, this render target
//! sources the fleet's font posture from ishou's typed Typography. One
//! Nerd Font, one calligraphic italic, fleet-wide — change in
//! `crates/ishou-tokens/src/typography.rs`, every foreign-app font
//! propagates on the next rebuild.
//!
//! Output format (matches `stylix.fonts.*` HM-module schema):
//!
//! ```nix
//! { pkgs }: {
//!   monospace = {
//!     name = "JetBrainsMono Nerd Font";
//!     package = pkgs.nerd-fonts.jetbrains-mono;
//!   };
//!   sansSerif = {
//!     name = "Inter";
//!     package = pkgs.inter;
//!   };
//!   …
//! }
//! ```
//!
//! Consumers import the result and set `stylix.fonts = import path { inherit pkgs; }`.

use ishou_tokens::TokenSet;

/// Render the canonical pleme-io stylix.fonts attrset.
///
/// Maps ishou's typed `Typography.mono_fonts` + family stacks to
/// stylix's four font slots (`monospace`, `sansSerif`, `serif`,
/// `emoji`). Each slot resolves to a `pkgs.<attr>` reference — the
/// HM build inherits the package from nixpkgs without operators
/// declaring it per-app.
#[must_use]
pub fn render(t: &TokenSet) -> String {
    let mono = &t.typography.mono_fonts;
    let mut out = String::new();
    out.push_str("# Generated by ishou-render::stylix_fonts — DO NOT EDIT\n");
    out.push_str("# Source of truth: pleme-io/ishou/crates/ishou-tokens/src/typography.rs\n");
    out.push_str("# Architecture:    pleme-io/theory/THEME-ARCHITECTURE.md\n");
    out.push_str("#\n");
    out.push_str("# Consumed as `stylix.fonts = import this { inherit pkgs; };`\n");
    out.push_str("# in the fleet's darwin / home-manager configuration.\n");
    out.push_str("{ pkgs }:\n{\n");

    // ── monospace ──────────────────────────────────────────────────
    out.push_str("  monospace = {\n");
    out.push_str(&format!("    name = \"{}\";\n", mono.primary));
    match mono.nerd_font_package_attr {
        Some(attr) => out.push_str(&format!(
            "    package = pkgs.nerd-fonts.{};\n", attr
        )),
        None => out.push_str("    package = pkgs.dejavu_fonts;\n"),
    }
    out.push_str("  };\n\n");

    // ── sans-serif ─────────────────────────────────────────────────
    // Inter is the canonical pleme-io sans — declared in ishou's
    // FontFamilies::sans stack. Package: pkgs.inter.
    out.push_str("  sansSerif = {\n");
    out.push_str("    name = \"Inter\";\n");
    out.push_str("    package = pkgs.inter;\n");
    out.push_str("  };\n\n");

    // ── serif ──────────────────────────────────────────────────────
    // Operator-side fallback — system fonts (Iowan Old Style on
    // macOS, Charter on Linux) generally beat any bundle. Stylix
    // requires *some* package; ship a thin charter equivalent that's
    // a known nixpkgs attr.
    out.push_str("  serif = {\n");
    out.push_str("    name = \"Charter\";\n");
    out.push_str("    package = pkgs.charter;\n");
    out.push_str("  };\n\n");

    // ── emoji ──────────────────────────────────────────────────────
    out.push_str("  emoji = {\n");
    out.push_str("    name = \"Noto Color Emoji\";\n");
    out.push_str("    package = pkgs.noto-fonts-emoji;\n");
    out.push_str("  };\n");

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use ishou_tokens::TokenSet;

    #[test]
    fn output_is_deterministic() {
        let t = TokenSet::pleme();
        assert_eq!(render(&t), render(&t));
    }

    #[test]
    fn monospace_resolves_to_nerd_fonts_jetbrains_mono() {
        let out = render(&TokenSet::pleme());
        assert!(out.contains("name = \"JetBrainsMono Nerd Font\""), "got:\n{out}");
        assert!(out.contains("package = pkgs.nerd-fonts.jetbrains-mono"), "got:\n{out}");
    }

    #[test]
    fn output_has_all_four_stylix_font_slots() {
        let out = render(&TokenSet::pleme());
        for slot in ["monospace", "sansSerif", "serif", "emoji"] {
            assert!(out.contains(&format!("{slot} = {{")), "missing {slot}");
        }
    }

    #[test]
    fn output_is_valid_nix_function_shape() {
        let out = render(&TokenSet::pleme());
        assert!(out.contains("{ pkgs }:"));
        assert!(out.trim_end().ends_with('}'));
    }

    #[test]
    fn header_documents_provenance() {
        let out = render(&TokenSet::pleme());
        assert!(out.contains("ishou-render"));
        assert!(out.contains("THEME-ARCHITECTURE.md"));
    }
}
